---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lena-manager
  namespace: ns-lena
spec:
  selector:
    matchLabels:
      name: lena-manager
  serviceName: lena-manager
  replicas: 1
  template:
    metadata:
      labels:
        name: lena-manager
    spec:
      containers:
      - name: lena-manager
        image: lenacloud/lena-manager:1.3.3.0-centos7-jdk11-openjdk
        imagePullPolicy: Always
        ports:
        - containerPort: 7700
#        livenessProbe:
#          httpGet:
#            path: /lena
#            port: 7700
#          initialDelaySeconds: 30
#          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: lena-manager-config
        volumeMounts:
        - name: lena-manager-repository
          mountPath: /usr/local/lena/repository
      volumes:
        - name: lena-manager-repository
          nfs:
            server: 192.168.0.11
            path: /anaki-nfs/lena-repository-1.3.3.0
      terminationGracePeriodSeconds: 0
      
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lena-manager-config
  namespace: ns-lena
data:
  LENA_MANAGER_DOMAIN_ENABLED: "Y"
  LENA_MANAGER_ADDRESS: "lena-manager.ns-lena.svc.cluster.local:7700"
  LENA_MANAGER_MONITORING_PORT: "16100"
  #LENA_USER: "lena"
  
---
apiVersion: v1
kind: Service
metadata:
  name: lena-manager
  namespace: ns-lena
spec:
  selector:
    name: lena-manager
  ports:
  - name: service
    protocol: TCP
    port: 7700
    targetPort: 7700
    nodePort: 30770
  - name: monitoring-tcp
    protocol: TCP
    port: 16100
    targetPort: 16100
  - name: monitoring-udp
    protocol: UDP
    port: 16100
    targetPort: 16100
  type: NodePort
